#! /bin/bash

#By Fernando Perez
#Script to select only autosomes and order by position the Log2Ratio and BAF files generated by GenomeStudio
#The resultant files will be used as input for ASCAT

#How to run it:
#	./select-Autosomes.sh Samples_March2021\LogRratio_samples.txt Samples_March2021\LogRratio_samples_autosomes.txt

INN=$1
OUT=$2

head -n 1 ${INN} >${OUT}".build"

grep -v "chr" ${INN} \
	| sort -k 2,2n -k 3,3n \
	| awk '{if ($2 ~ /[1-9]/) print}' >>${OUT}".build"
grep -v "chr" ${INN} | grep -P "\tX\t" \
	| sort -k 2,2n -k 3,3n >>${OUT}".build" \
&& mv ${OUT}".build" ${OUT}
